/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_free_aiassist_asr_sherpa_SherpaJNI */

#ifndef _Included_com_free_aiassist_asr_sherpa_SherpaJNI
#define _Included_com_free_aiassist_asr_sherpa_SherpaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_free_aiassist_asr_sherpa_SherpaJNI
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_free_aiassist_asr_sherpa_SherpaJNI_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_free_aiassist_asr_sherpa_SherpaJNI
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_free_aiassist_asr_sherpa_SherpaJNI_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_free_aiassist_asr_sherpa_SherpaJNI
 * Method:    restart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_free_aiassist_asr_sherpa_SherpaJNI_restart
  (JNIEnv *, jobject);

/*
 * Class:     com_free_aiassist_asr_sherpa_SherpaJNI
 * Method:    fullTranscribe
 * Signature: ([F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_free_aiassist_asr_sherpa_SherpaJNI_fullTranscribe
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_free_aiassist_asr_sherpa_SherpaJNI
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_free_aiassist_asr_sherpa_SherpaJNI_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
